include:
- api-source.zip
kind: ArchiveUploadSpec
name: api-source-zip-FMMD

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: api-src
  namespace: default
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://api-source-zip-FMMD
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-03-20T16:31:10Z"
