apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: download
  namespace: default
spec:
  createingress: true
  functionref:
    functionweights: null
    name: download
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /download
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /download
