apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: transon
  namespace: default
spec:
  createingress: true
  functionref:
    functionweights: null
    name: frontend
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /transon
    tls: ""
  keepPrefix: true
  method: ""
  methods:
  - GET
  prefix: /transon
  relativeurl: ""
