apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: upload
  namespace: default
spec:
  createingress: true
  functionref:
    functionweights: null
    name: upload
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /upload
    tls: ""
  method: ""
  methods:
  - POST
  prefix: ""
  relativeurl: /upload
