version: "3"
services:
  minio-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minio
    restart: on-failure
    entrypoint: /entrypoint.sh
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
