version: '3'
services:
  postgres:
    container_name: pg
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
